[package]
name = "rt-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rtc"
path = "src/main.rs"

[dependencies]
rt-common.path = "../common"
rt-driver.path = "../driver"
rt-lexer.path = "../lexer"
rt-parser.path = "../parser"
rt-ast.path = "../ast"
rt-semantic.path = "../semantic"
rt-codegen.path = "../codegen"
clap.workspace = true
inkwell.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
