use std::fmt;

use crate::span::Span;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Eof,

    Ident,
    KwLet,
    KwMut,
    KwFn,
    KwIf,
    KwElse,
    KwLoop,
    KwWhile,
    KwFor,
    KwIn,
    KwMatch,
    KwReturn,
    KwBreak,
    KwContinue,
    KwStruct,
    KwEnum,
    KwImpl,
    KwTrait,
    KwMod,
    KwPub,
    KwUse,
    KwSelf,
    KwSuper,
    KwCrate,
    KwAs,
    KwRef,
    KwTrue,
    KwFalse,
    KwMove,
    KwConst,
    KwStatic,
    KwWhere,
    KwType,
    KwDyn,
    KwUnsafe,
    KwAsync,
    KwAwait,
    KwSizeOf,
    KwBox,
    KwSelfType,
    KwSelfLower,
    KwSelfStatic,

    Integer,
    Float,
    Char,
    Byte,
    String,
    ByteString,
    Bool,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Not,
    And,
    Or,
    AndAnd,
    OrOr,
    Shl,
    Shr,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    CaretEq,
    AndEq,
    OrEq,
    ShlEq,
    ShrEq,
    Eq,
    EqEq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    Dot,
    DotDot,
    DotDotEq,
    Comma,
    Semi,
    Colon,
    PathSep,
    RArrow,
    FatArrow,
    At,
    Underscore,
    Pound,
    Dollar,
    Question,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,

    DocComment,
    LineComment,
    BlockComment,

    Shebang,

    Unknown,
}

impl TokenKind {
    pub fn from_keyword(s: &str) -> Option<TokenKind> {
        match s {
            "let" => Some(TokenKind::KwLet),
            "mut" => Some(TokenKind::KwMut),
            "fn" => Some(TokenKind::KwFn),
            "if" => Some(TokenKind::KwIf),
            "else" => Some(TokenKind::KwElse),
            "loop" => Some(TokenKind::KwLoop),
            "while" => Some(TokenKind::KwWhile),
            "for" => Some(TokenKind::KwFor),
            "in" => Some(TokenKind::KwIn),
            "match" => Some(TokenKind::KwMatch),
            "return" => Some(TokenKind::KwReturn),
            "break" => Some(TokenKind::KwBreak),
            "continue" => Some(TokenKind::KwContinue),
            "struct" => Some(TokenKind::KwStruct),
            "enum" => Some(TokenKind::KwEnum),
            "impl" => Some(TokenKind::KwImpl),
            "trait" => Some(TokenKind::KwTrait),
            "mod" => Some(TokenKind::KwMod),
            "pub" => Some(TokenKind::KwPub),
            "use" => Some(TokenKind::KwUse),
            "self" => Some(TokenKind::KwSelfLower),
            "Self" => Some(TokenKind::KwSelfType),
            "super" => Some(TokenKind::KwSuper),
            "crate" => Some(TokenKind::KwCrate),
            "as" => Some(TokenKind::KwAs),
            "ref" => Some(TokenKind::KwRef),
            "true" => Some(TokenKind::KwTrue),
            "false" => Some(TokenKind::KwFalse),
            "move" => Some(TokenKind::KwMove),
            "const" => Some(TokenKind::KwConst),
            "static" => Some(TokenKind::KwStatic),
            "where" => Some(TokenKind::KwWhere),
            "type" => Some(TokenKind::KwType),
            "dyn" => Some(TokenKind::KwDyn),
            "unsafe" => Some(TokenKind::KwUnsafe),
            "async" => Some(TokenKind::KwAsync),
            "await" => Some(TokenKind::KwAwait),
            _ => None,
        }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Eof => write!(f, "EOF"),
            TokenKind::Ident => write!(f, "identifier"),
            TokenKind::KwLet => write!(f, "let"),
            TokenKind::KwMut => write!(f, "mut"),
            TokenKind::KwFn => write!(f, "fn"),
            TokenKind::KwIf => write!(f, "if"),
            TokenKind::KwElse => write!(f, "else"),
            TokenKind::KwLoop => write!(f, "loop"),
            TokenKind::KwWhile => write!(f, "while"),
            TokenKind::KwFor => write!(f, "for"),
            TokenKind::KwIn => write!(f, "in"),
            TokenKind::KwMatch => write!(f, "match"),
            TokenKind::KwReturn => write!(f, "return"),
            TokenKind::KwBreak => write!(f, "break"),
            TokenKind::KwContinue => write!(f, "continue"),
            TokenKind::KwStruct => write!(f, "struct"),
            TokenKind::KwEnum => write!(f, "enum"),
            TokenKind::KwImpl => write!(f, "impl"),
            TokenKind::KwTrait => write!(f, "trait"),
            TokenKind::KwMod => write!(f, "mod"),
            TokenKind::KwPub => write!(f, "pub"),
            TokenKind::KwUse => write!(f, "use"),
            TokenKind::KwSelf => write!(f, "self"),
            TokenKind::KwSuper => write!(f, "super"),
            TokenKind::KwCrate => write!(f, "crate"),
            TokenKind::KwAs => write!(f, "as"),
            TokenKind::KwRef => write!(f, "ref"),
            TokenKind::KwTrue => write!(f, "true"),
            TokenKind::KwFalse => write!(f, "false"),
            TokenKind::KwMove => write!(f, "move"),
            TokenKind::KwConst => write!(f, "const"),
            TokenKind::KwStatic => write!(f, "static"),
            TokenKind::KwWhere => write!(f, "where"),
            TokenKind::KwType => write!(f, "type"),
            TokenKind::KwDyn => write!(f, "dyn"),
            TokenKind::KwUnsafe => write!(f, "unsafe"),
            TokenKind::KwAsync => write!(f, "async"),
            TokenKind::KwAwait => write!(f, "await"),
            TokenKind::KwSizeOf => write!(f, "sizeof"),
            TokenKind::KwBox => write!(f, "box"),
            TokenKind::KwSelfType => write!(f, "Self"),
            TokenKind::KwSelfLower => write!(f, "self"),
            TokenKind::KwSelfStatic => write!(f, "Self"),
            TokenKind::Integer => write!(f, "integer"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::Char => write!(f, "char"),
            TokenKind::Byte => write!(f, "byte"),
            TokenKind::String => write!(f, "string"),
            TokenKind::ByteString => write!(f, "byte string"),
            TokenKind::Bool => write!(f, "bool"),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::Caret => write!(f, "^"),
            TokenKind::Not => write!(f, "!"),
            TokenKind::And => write!(f, "&"),
            TokenKind::Or => write!(f, "|"),
            TokenKind::AndAnd => write!(f, "&&"),
            TokenKind::OrOr => write!(f, "||"),
            TokenKind::Shl => write!(f, "<<"),
            TokenKind::Shr => write!(f, ">>"),
            TokenKind::PlusEq => write!(f, "+="),
            TokenKind::MinusEq => write!(f, "-="),
            TokenKind::StarEq => write!(f, "*="),
            TokenKind::SlashEq => write!(f, "/="),
            TokenKind::PercentEq => write!(f, "%="),
            TokenKind::CaretEq => write!(f, "^="),
            TokenKind::AndEq => write!(f, "&="),
            TokenKind::OrEq => write!(f, "|="),
            TokenKind::ShlEq => write!(f, "<<="),
            TokenKind::ShrEq => write!(f, ">>="),
            TokenKind::Eq => write!(f, "="),
            TokenKind::EqEq => write!(f, "=="),
            TokenKind::Ne => write!(f, "!="),
            TokenKind::Lt => write!(f, "<"),
            TokenKind::Gt => write!(f, ">"),
            TokenKind::Le => write!(f, "<="),
            TokenKind::Ge => write!(f, ">="),
            TokenKind::Dot => write!(f, "."),
            TokenKind::DotDot => write!(f, ".."),
            TokenKind::DotDotEq => write!(f, "..="),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Semi => write!(f, ";"),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::PathSep => write!(f, "::"),
            TokenKind::RArrow => write!(f, "->"),
            TokenKind::FatArrow => write!(f, "=>"),
            TokenKind::At => write!(f, "@"),
            TokenKind::Underscore => write!(f, "_"),
            TokenKind::Pound => write!(f, "#"),
            TokenKind::Dollar => write!(f, "$"),
            TokenKind::Question => write!(f, "?"),
            TokenKind::LParen => write!(f, "("),
            TokenKind::RParen => write!(f, ")"),
            TokenKind::LBrace => write!(f, "{{"),
            TokenKind::RBrace => write!(f, "}}"),
            TokenKind::LBracket => write!(f, "["),
            TokenKind::RBracket => write!(f, "]"),
            TokenKind::DocComment => write!(f, "doc comment"),
            TokenKind::LineComment => write!(f, "line comment"),
            TokenKind::BlockComment => write!(f, "block comment"),
            TokenKind::Shebang => write!(f, "shebang"),
            TokenKind::Unknown => write!(f, "unknown"),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Token { kind, span }
    }
}
